import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/nav";
import { auth } from "@/auth";
import Home from "@/components/home";
import "./globals.css";
import { checkIfCompleteUser } from "@/lib/utils/utilFunctions";
import GetDetails from "@/components/getDetails";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  const isLoggedIn = !!session?.user;
  const isUserProfileComplete =
    isLoggedIn && session?.user
      ? await checkIfCompleteUser(session.user)
      : false;

  return (
    <html className="h-full" lang="en">
      <body className={`${inter.className} h-full flex flex-col`}>
        <Nav isUserProfileComplete={isUserProfileComplete} />
        <div className="flex justify-center text-lg mt-6 mb-12">
          {session?.user && isLoggedIn && isUserProfileComplete && (
            <h3>Gym Timings: 5:00 AM to 9:00AM & 4:00 PM to 9:00 PM</h3>
          )}
        </div>
        {!isLoggedIn && <Home />}
        {session?.user && isLoggedIn && !isUserProfileComplete && (
          <GetDetails user={session.user} />
        )}
        {session?.user && isLoggedIn && isUserProfileComplete && children}
      </body>
    </html>
  );
}
